# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Testcicdstage-tms

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          # npm run test --if-present
          
      
      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: node-app
      #     path: .

  deploy:
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Testcicdstage-tms'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB19FB0889E04566AD62186546168769 }}
          package: .
      - name: Start the application
        run: |
          echo "Starting the application..."
          ls
          npm start
