# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions {test..11}

name: Build and deploy Node.js app to Azure Web App - Testcicdstage-tms

on:
  push:
    branches:
      - staging
  workflow_dispatch:
  
permissions:
  contents: write
      

jobs:
  build:
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    # environment:
    #   name: 'Production'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          # npm run build --if-present
          # npm run test --if-present
          echo "hi"
          ls 
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r    

      # - name: Archive step
      #   run:  Compress-Archive . release.zip
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          # path: .
          path: release.zip
      # ===========================
      # - name: 'Deploy to Azure Web App'
      #   uses: azure/webapps-deploy@v2
      #   id: deploy-to-webapp
      #   with:
      #     app-name: 'Testcicdstage-tms'
      #     slot-name: 'Production'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB19FB0889E04566AD62186546168769 }}
      #     package: .    

  deploy:
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      # - name: Expand Artifact
      #   run: Expand-Archive release.zip   

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Testcicdstage-tms'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB19FB0889E04566AD62186546168769 }}
          package: .

 
    
